pyproject.toml: bump dependency versions to limit search space
crossbar==22.4.1 raises RuntimeErrors:

    Traceback (most recent call last):
    File "venv/lib/python3.9/site-packages/labgrid/remote/coordinator.py", line 13, in <module>
    from autobahn.asyncio.wamp import ApplicationRunner, ApplicationSession
    File "venv/lib/python3.9/site-packages/autobahn/asyncio/__init__.py", line 32, in <module>
    from autobahn.asyncio.websocket import \
    File "venv/lib/python3.9/site-packages/autobahn/asyncio/websocket.py", line 36, in <module>
    from autobahn.wamp import websocket
    File "venv/lib/python3.9/site-packages/autobahn/wamp/websocket.py", line 32, in <module>
    from autobahn.websocket import protocol
    File "venv/lib/python3.9/site-packages/autobahn/websocket/protocol.py", line 2533, in <module>
    class WebSocketServerProtocol(WebSocketProtocol):
    File "venv/lib/python3.9/site-packages/autobahn/websocket/protocol.py", line 2538, in WebSocketServerProtocol
    log = txaio.make_logger()
    File "venv/lib/python3.9/site-packages/txaio/_unframework.py", line 41, in _throw_usage_error
    raise RuntimeError(
    RuntimeError: To use txaio, you must first select a framework with .use_twisted() or .use_asyncio()

Because it makes no sense to have a lower autobahn version than crossbar
version, limit both to >=22.5.1

Also bump various packages' versions to their recent releases, otherwise
pip's dependency resolution takes forever. This is probably caused by
the large dependency trees of crossbar and autobahn.

Signed-off-by: Bastian Krause <bst@pengutronix.de>