util/expect: make PtxExpect proper pexpext.spawn subclass
Using super() fixes..

  AttributeError: 'PtxExpect' object has no attribute 'ignorecase'

..happening during tests when mocking pexpect.spawn's expect() method.

Signed-off-by: Bastian Krause <bst@pengutronix.de>