crossbar-requirements.txt: duplicate crossbar extra to crossbar-requirements.txt
This is preparatory work to install crossbar in a dedicated virtualenv
This should reduce dependency conflicts caused by shared dependencies
between crossbar and labgrid. No pytest plugins installed by crossbar
dependencies are installed in the labgrid virtualenv anymore.

For the time being, keep crossbar's version pinned, because more recent
versions break Python 3.11 support due to crossbar dependencies using
Python API that has been deprecated since Python 3.0 [1]. We can still
loosen this later.

crossbar's autobahn dependency needs to be limited, because it uses API
dropped with [2] (contained in autobahn since 22.5.1):

  Traceback (most recent call last):
    File "/home/runner/work/labgrid/labgrid/crossbar-venv/bin/crossbar", line 8, in <module>
      sys.exit(run())
    File "/home/runner/work/labgrid/labgrid/crossbar-venv/lib/python3.10/site-packages/crossbar/__init__.py", line 203, in run
      return main(exename, args, reactor, personality_klass)
    File "/home/runner/work/labgrid/labgrid/crossbar-venv/lib/python3.10/site-packages/crossbar/node/main.py", line 1328, in main
      options.func(options, reactor=reactor, personality=personality)
    File "/home/runner/work/labgrid/labgrid/crossbar-venv/lib/python3.10/site-packages/crossbar/node/main.py", line 846, in _run_command_start
      node.load_keys(options.cbdir)
    File "/home/runner/work/labgrid/labgrid/crossbar-venv/lib/python3.10/site-packages/crossbar/node/node.py", line 190, in load_keys
      was_new, self._node_key = _maybe_generate_key(cbdir)
    File "/home/runner/work/labgrid/labgrid/crossbar-venv/lib/python3.10/site-packages/crossbar/common/key.py", line 295, in _maybe_generate_key
      return was_new, cryptosign.SigningKey(privkey)
  AttributeError: module 'autobahn.wamp.cryptosign' has no attribute 'SigningKey'

[1] crossbar requires eth-abi==2.2.0, which requires parsimonious<0.9.0,
    leading to 0.8.1 being installed, which is affected by
    https://github.com/erikrose/parsimonious/issues/225
[2] https://github.com/crossbario/autobahn-python/commit/05da974a97eba2e742d5adba1abdd5f9e6fe626b

Signed-off-by: Bastian Krause <bst@pengutronix.de>